DELETE http://localhost:3003/api/blogs/5d873ad9014b952ff470ed5b
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMTIzIiwiaWQiOiI1ZDg3NDI4MWIzMjYwMTRhODAyZTA2ZjgiLCJpYXQiOjE1NjkxNDU0ODl9.7-65PPKa3veTKZCgjwIMXhmuBnmWbKfTJcprz5xGbeE
