POST http://localhost:3003/api/blogs/5da5c9dc1d31b551dc4ed60b/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMTIzNCIsImlkIjoiNWQ4NmRmNzUxOGE2ZWQ0NWQ4YzBkMjZmIiwiaWF0IjoxNTY5MTQzNDU1fQ.MhijzyVsgHvCViF4kcFIJeLlO9s7IXMVm5d7IpKuQUQ

{
    "comment": "Comment 2",
    "blog": "5da5c9dc1d31b551dc4ed60b"
}